plugins {
    id 'java-library'
    id 'maven-publish'
}

group = "kernel"
version = "1.0.0"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    api 'kernel:common:1.0.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
